version: "3.9"
services:
  db:
    image: postgres:14
    container_name: gestor-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: franco
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: gestor_passwords
    ports:
      - "5433:5432"
    volumes:
      - gestor_pgdata:/var/lib/postgresql/data

volumes:
  gestor_pgdata:
